version: '3.8'

services:
  mysqldb:
    image: mysql:8.0.30
    restart: always
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    environment:
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
      MYSQL_USER: ${MYSQLDB_USER}
      MYSQL_PASSWORD: ${MYSQLDB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "localhost"
    volumes:
      - mysql-data:/var/lib/mysql
      - mysqld-data:/var/run/mysqld

  java:
    command: mvn spring-boot:run
    depends_on:
      - mysqldb
    build: .
    env_file: ./.env
    ports:
      - '8080:8080'
    volumes:
      - ./src:/buscapatas/src
      - m2-data:/root/.m2
    stdin_open: true
    tty: true

volumes:
  mysql-data:
  mysqld-data:
  m2-data:
